def keyword_field() -> dict:
    return {"type": "keyword"}


def text_field() -> dict:
    return {"type": "text", "fields": {"keyword": {"type": "keyword", "ignore_above": 256}}}


def double_field() -> dict:
    return {"type": "double"}


def date_field() -> dict:
    return {"type": "date"}


ACCOUNT_INDEX = "ibkr_account_daily_snapshot_v1"
POSITION_INDEX = "ibkr_position_daily_snapshot_v1"
TRADE_INDEX = "ibkr_trade_records_v1"
CASH_FLOW_INDEX = "ibkr_cash_flow_records_v1"
PRICE_HISTORY_INDEX = "ibkr_symbol_price_history_v1"


INDEX_DEFINITIONS = {
    ACCOUNT_INDEX: {
        "settings": {"number_of_shards": 1, "number_of_replicas": 0},
        "mappings": {
            "properties": {
                "account_id": keyword_field(),
                "report_date": date_field(),
                "currency": keyword_field(),
                "total_equity": double_field(),
                "cash": double_field(),
                "stock_value": double_field(),
                "options_value": double_field(),
                "funds_value": double_field(),
                "crypto_value": double_field(),
                "interest_accruals": double_field(),
                "dividend_accruals": double_field(),
                "margin_financing_charge_accruals": double_field(),
                "cnav_starting_value": double_field(),
                "cnav_ending_value": double_field(),
                "cnav_mtm": double_field(),
                "cnav_realized": double_field(),
                "cnav_change_in_unrealized": double_field(),
                "cnav_dividends": double_field(),
                "cnav_interest": double_field(),
                "cnav_commissions": double_field(),
                "cnav_broker_fees": double_field(),
                "cnav_net_fx_trading": double_field(),
                "cnav_twr": double_field(),
                "crtt_dividends_mtd": double_field(),
                "crtt_dividends_ytd": double_field(),
                "crtt_broker_interest_mtd": double_field(),
                "crtt_broker_interest_ytd": double_field(),
                "crtt_commissions_mtd": double_field(),
                "crtt_commissions_ytd": double_field(),
                "crtt_starting_cash": double_field(),
                "crtt_ending_cash": double_field(),
                "fifo_total_realized_pnl": double_field(),
                "fifo_total_unrealized_pnl": double_field(),
                "fifo_total_pnl": double_field(),
                "source_file_name": keyword_field(),
                "source_query_type": keyword_field(),
                "ingested_at": date_field(),
            }
        },
    },
    POSITION_INDEX: {
        "settings": {"number_of_shards": 1, "number_of_replicas": 0},
        "mappings": {
            "properties": {
                "account_id": keyword_field(),
                "report_date": date_field(),
                "currency": keyword_field(),
                "asset_class": keyword_field(),
                "sub_category": keyword_field(),
                "symbol": keyword_field(),
                "description": text_field(),
                "conid": keyword_field(),
                "security_id": keyword_field(),
                "security_id_type": keyword_field(),
                "isin": keyword_field(),
                "figi": keyword_field(),
                "listing_exchange": keyword_field(),
                "issuer": text_field(),
                "issuer_country_code": keyword_field(),
                "quantity": double_field(),
                "mark_price": double_field(),
                "position_value": double_field(),
                "open_price": double_field(),
                "cost_basis_price": double_field(),
                "average_cost_price": double_field(),
                "cost_basis_money": double_field(),
                "percent_of_nav": double_field(),
                "fifo_pnl_unrealized": double_field(),
                "side": keyword_field(),
                "shares_at_ib": double_field(),
                "shares_borrowed": double_field(),
                "shares_lent": double_field(),
                "net_shares": double_field(),
                "total_realized_pnl": double_field(),
                "realized_pnl_percent": double_field(),
                "total_unrealized_pnl": double_field(),
                "unrealized_pnl_percent": double_field(),
                "total_fifo_pnl": double_field(),
                "previous_day_change_percent": double_field(),
                "realized_pnl_mtd": double_field(),
                "realized_pnl_ytd": double_field(),
                "mark_to_market_mtd": double_field(),
                "mark_to_market_ytd": double_field(),
                "source_file_name": keyword_field(),
                "source_query_type": keyword_field(),
                "ingested_at": date_field(),
            }
        },
    },
    TRADE_INDEX: {
        "settings": {"number_of_shards": 1, "number_of_replicas": 0},
        "mappings": {
            "properties": {
                "account_id": keyword_field(),
                "currency": keyword_field(),
                "asset_class": keyword_field(),
                "sub_category": keyword_field(),
                "symbol": keyword_field(),
                "description": text_field(),
                "conid": keyword_field(),
                "security_id": keyword_field(),
                "security_id_type": keyword_field(),
                "isin": keyword_field(),
                "figi": keyword_field(),
                "listing_exchange": keyword_field(),
                "trade_id": keyword_field(),
                "related_trade_id": keyword_field(),
                "report_date": date_field(),
                "trade_date": date_field(),
                "date_time": date_field(),
                "settle_date_target": date_field(),
                "transaction_type": keyword_field(),
                "exchange": keyword_field(),
                "quantity": double_field(),
                "trade_price": double_field(),
                "trade_money": double_field(),
                "proceeds": double_field(),
                "taxes": double_field(),
                "ib_commission": double_field(),
                "ib_commission_currency": keyword_field(),
                "net_cash": double_field(),
                "close_price": double_field(),
                "open_close_indicator": keyword_field(),
                "notes_codes": keyword_field(),
                "cost_basis": double_field(),
                "fifo_pnl_realized": double_field(),
                "mtm_pnl": double_field(),
                "orig_trade_price": double_field(),
                "orig_trade_date": date_field(),
                "orig_trade_id": keyword_field(),
                "orig_order_id": keyword_field(),
                "orig_transaction_id": keyword_field(),
                "buy_sell": keyword_field(),
                "ib_order_id": keyword_field(),
                "transaction_id": keyword_field(),
                "ib_exec_id": keyword_field(),
                "related_transaction_id": keyword_field(),
                "brokerage_order_id": keyword_field(),
                "order_reference": keyword_field(),
                "exch_order_id": keyword_field(),
                "ext_exec_id": keyword_field(),
                "order_time": date_field(),
                "open_date_time": date_field(),
                "holding_period_date_time": date_field(),
                "when_realized": date_field(),
                "when_reopened": date_field(),
                "order_type": keyword_field(),
                "trader_id": keyword_field(),
                "is_api_order": {"type": "boolean"},
                "accrued_interest": double_field(),
                "initial_investment": double_field(),
                "unbc_total_commission": double_field(),
                "unbc_broker_execution_charge": double_field(),
                "unbc_broker_clearing_charge": double_field(),
                "unbc_third_party_execution_charge": double_field(),
                "unbc_third_party_clearing_charge": double_field(),
                "unbc_third_party_regulatory_charge": double_field(),
                "unbc_reg_finra_trading_activity_fee": double_field(),
                "unbc_reg_section31_transaction_fee": double_field(),
                "unbc_reg_other": double_field(),
                "unbc_other": double_field(),
                "source_file_name": keyword_field(),
                "source_query_type": keyword_field(),
                "ingested_at": date_field(),
            }
        },
    },
    CASH_FLOW_INDEX: {
        "settings": {"number_of_shards": 1, "number_of_replicas": 0},
        "mappings": {
            "properties": {
                "account_id": keyword_field(),
                "currency": keyword_field(),
                "asset_class": keyword_field(),
                "sub_category": keyword_field(),
                "symbol": keyword_field(),
                "description": text_field(),
                "date_time": date_field(),
                "settle_date": date_field(),
                "available_for_trading_date": date_field(),
                "amount": double_field(),
                "fx_rate_to_base": double_field(),
                "amount_in_base": double_field(),
                "flow_direction": keyword_field(),
                "flow_type": keyword_field(),
                "dividend_type": keyword_field(),
                "transaction_id": keyword_field(),
                "trade_id": keyword_field(),
                "code": keyword_field(),
                "report_date": date_field(),
                "ex_date": date_field(),
                "client_reference": keyword_field(),
                "action_id": keyword_field(),
                "level_of_detail": keyword_field(),
                "source_file_name": keyword_field(),
                "source_query_type": keyword_field(),
                "ingested_at": date_field(),
            }
        },
    },
    PRICE_HISTORY_INDEX: {
        "settings": {"number_of_shards": 1, "number_of_replicas": 0},
        "mappings": {
            "properties": {
                "account_id": keyword_field(),
                "report_date": date_field(),
                "currency": keyword_field(),
                "asset_class": keyword_field(),
                "sub_category": keyword_field(),
                "symbol": keyword_field(),
                "description": text_field(),
                "conid": keyword_field(),
                "security_id": keyword_field(),
                "security_id_type": keyword_field(),
                "isin": keyword_field(),
                "figi": keyword_field(),
                "listing_exchange": keyword_field(),
                "issuer": text_field(),
                "issuer_country_code": keyword_field(),
                "close_price": double_field(),
                "previous_close_price": double_field(),
                "open_price": double_field(),
                "high_price": double_field(),
                "low_price": double_field(),
                "prior_mtm_pnl": double_field(),
                "fx_rate_to_base": double_field(),
                "source_file_name": keyword_field(),
                "source_query_type": keyword_field(),
                "ingested_at": date_field(),
            }
        },
    },
}
